### ISSUE TITLE
Allow running a command directly from plugin settings (instead of launching a file with it)

### ISSUE THREAD

**Issue by eugenesvk** [tonsky/Sublime-Executor#4]
As far as I understand, it's only possible to run an executable file.
For some commands (like a generic invokation of a language repl that's not project-specific) there is no need for the file to be present, and it would be great if you could run your Executor with a specified command
This would be similar to a build command, but as far as I understood from quick googling and reading a couple of unanswered SO posts, you can't cancel a long-running build command like a repl (and the ouptut panel doesn't accept input)
Hence I thought maybe your Executor could support such a use case

**Comment by tonsky** [comment]
Done, see 1.1

**Comment by eugenesvk** [comment]
It's still not available via package control, and I suspect it might be due to some version resolution bug since your `1.1` version has a different format than `1.0.1`, so it's considered a downgrade like 11<101
Would you please add a new tag `1.1.0`?

**Comment by tonsky** [comment]
Added

**Comment by eugenesvk** [comment]
Thanks, now it's updated, though when I run the command, nothing happens, I'd expect it to prompt me for the command and run it (but your shortcut example works)
I get a missing ShellInputHandler error
```
Traceback (most recent call last):
  File "../Lib/python38/sublime_plugin.py", line 1603, in create_input_handler_
    return self.input(args)
  File "../Installed Packages/Executor.sublime-package/package.py", line 244, in input
NameError: name 'ShellInputHandler' is not defined
Traceback (most recent call last):
  File "../Lib/python38/sublime_plugin.py", line 1659, in run_
    return self.run()
TypeError: run() missing 1 required positional argument: 'command'
```

**Comment by tonsky** [comment]
Oops, pushed 1.1.1
